version: '3.8'

services:
  api:
    build: .
    container_name: credit_risk_api
    ports:
      - "8000:8000"
    volumes:
      # Mount the src directory for live reloading during development
      - ./src:/app/src
      # Mount the mlruns directory to access model artifacts
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
